// Copyright 2026 The Xerxes-Agents Author @erfanzar (Erfan Zare Chavoshi).
// Licensed under the Apache License, Version 2.0.

/** Shared read-only guide; describes entry points, not live connection health. */
export const FEATURES_GUIDE = [
  'EXPLORE XERXES',
  'Close this guide, then type a command to get started.',
  '',
  'DELEGATE WORK',
  '/agents       Inspect working agents and their results. F6 also opens agents.',
  '/config       Choose provider, model and reasoning for light, balanced and smart agents.',
  '/init         Ask the model to inspect this repo and create missing specialists and workflows.',
  '              Existing .xerxes/agents load automatically; ask for a specialist by name.',
  '',
  'KEEP WORK MOVING',
  '/terminals    Inspect background shells, read output and send input. Shortcut: F8.',
  '/runs         Review run history, unread results and supported cancellation actions.',
  '/monitors     Watch terminals, files or configured network sources. Press N to create.',
  '/schedules    Create or edit scheduled jobs. Press N to create; P to pause/resume.',
  '/loop         Set up bounded follow-ups for this conversation.',
  '/goal         Inspect the goal and todos. Shortcut: F10.',
  '              Scheduled work needs the owning daemon running.',
  '',
  'REVIEW AND RECOVER',
  '/diff         Review workspace changes. Shortcut: F7.',
  '/snapshots    Browse snapshots and preview a restore.',
  '/workspaces   Inspect retained agent workspaces.',
  '/context      Inspect conversation context and memory.',
  '',
  'CONNECT AND CUSTOMIZE',
  '/provider     Choose a provider and model for this conversation.',
  '/reasoning    Choose the conversation reasoning effort.',
  '/config mcp   Configure MCP servers; /config lsp configures language servers.',
  '/machine      Open saved remote workspaces over SSH; exit to return to this chat.',
  '/custom-agents Create or edit .xerxes/agents specialists. N new · Enter edit · Ctrl+S save.',
  '/skills       List skills; search <query> or install <local-directory-or-SKILL.md>.',
  '/plugins      List plugins; install <local-module.ts>, enable <name>, disable <name>.',
  '/browser      Connect to an already-running Chromium CDP endpoint.',
  '/reload       Reload configuration and project definitions after edits.',
  '              External connections require your configuration; this guide does not test access.',
  '',
  'SETUP NOTES',
  'Remote hosts need Xerxes installed and providers configured. /machine uses your SSH config.',
  'Skill installs copy local bundles and assets. Plugin installs enable local native tool modules',
  'in place; keep their source files. Network marketplaces are not connected.',
  '',
  '/help         All commands and keyboard shortcuts.',
].join('\n')
